# Generated by Django 2.2.4 on 2020-11-17 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_manger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='manger',
        ),
    ]
